version: 2
updates:
  # Maintain dependencies for npm (Frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for pip (Backend)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
