version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: market-watcher-dynamodb
    ports:
      - "8000:8000"

    volumes:
      - "./dynamodb_data:/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    restart: always

# ローカルDynamoDBのデータを保存するフォルダは自動的にプロジェクト直下に作成されます。
