name: AWS SAM CI

on:
  push:
    branches: [ main ]
    paths:
      - 'template.yaml'
      - '.github/workflows/aws.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'template.yaml'
      - '.github/workflows/aws.yml'

jobs:
  aws-sam-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Validate SAM Template
        run: sam validate --no-resolve-parameters
